title: Home
views:
  - title: Control
    cards:
      - type: entities
        entities:
          - scene.normal
          - scene.dark
          - scene.away
          - script.night
          - scene.movie
      - type: thermostat
        entity: climate.woonkamer
      - type: entities
        entities:
          - script.open_covers
          - script.close_covers
  - title: Media
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - input_select.radio_station
          - script.radio
      - type: media-control
        entity: media_player.lg_webos_smart_tv
      - type: media-control
        entity: media_player.nad7050
      - type: media-control
        entity: media_player.chromecast_audio
      - type: entities
        entities:
          - scene.movie
          - scene.dark
          - scene.normal
          - script.netflix
          - script.youtube
          - script.npo
          - script.disney
          - entity: switch.tradfri_outlet
            name: stereo power
  - title: Lights
    cards:
      - type: light
        entity: light.livingroom_back
      - type: light
        entity: light.livingroom_left
      - type: light
        entity: light.livingroom_right
      - type: light
        entity: light.livingroom_corner
      - type: entities
        entities:
          - switch.bookcase_light
          - switch.kitchen_light_left
          - switch.kitchen_light_right
      - type: light
        entity: light.reading
      - type: light
        entity: light.bedroomstrip
  - title: Data
    cards:
      - type: picture-entity
        entity: camera.buienradar_loop
      - type: weather-forecast
        entity: weather.br_unknown_station
      - type: glance
        show_icon: false
        title: Temperature
        entities:
          - entity: sensor.hall_temperature_2
            name: Hall
          - entity: sensor.qubino_zmnhcdx_flush_shutter_temperature
            name: Upstairs
          - entity: sensor.kitchen_temperature_2
            name: Kitchen
          - entity: sensor.restroom_temperature_2
            name: Restroom
      - type: glance
        show_icon: false
        title: Power
        entities:
          - entity: sensor.power_consumption
            name: Consumption
          - entity: sensor.power_production
            name: Production
          - entity: sensor.gas_consumption
            name: Gas
      - type: glance
        show_icon: false
        title: Network
        entities:
          - entity: sensor.download
            name: Download
          - entity: sensor.upload
            name: Upload
      - type: glance
        show_icon: false
        title: Battery
        entities:
          - entity: sensor.hue_battery_hall
            name: Hall
          - entity: sensor.hue_battery_restroom
            name: Restroom
          - entity: sensor.hue_battery_scullery
            name: Scullery
          - entity: sensor.tradfri_on_off_switch
            name: Reading switch
      - type: glance
        title: Light
        show_icon: false
        entities:
          - entity: sensor.hue_light_hall
            name: Hall
          - entity: sensor.hue_light_scullery
            name: Scullery
          - entity: sensor.hue_light_restroom
            name: Restroom
      - type: glance
        title: sun
        show_icon: false
        entities:
          - entity: sensor.sunrise
            name: sunrise
          - entity: sensor.sunset
            name: sunset
      - type: sensor
        entity: sensor.rova_paper_date
        name: Rova papier
      
  - title: Covers
    cards:
      - type: entities
        entities:
          - entity: cover.qubino_zmnhcdx_flush_shutter_switch
            name: kitchen
          - entity: cover.qubino_zmnhcdx_flush_shutter_switch_2
            name: livingroom_left
          - entity: cover.qubino_zmnhcdx_flush_shutter_switch_3
            name: livingroom_right
          - entity: cover.qubino_zmnhcdx_flush_shutter_switch_4
            name: upstairs_side
          - entity: cover.qubino_zmnhcdx_flush_shutter_switch_5
            name: upstairs_front
          - entity: cover.grote_schuifpui
            name: grote_schuifpui
          - entity: cover.kleine_schuifpui
            name: kleine_schuifpui
  - title: Clock
    cards:
      - type: entities
        entities:
          - sensor.alarm_clock_time
          - input_number.alarm_clock_hour
          - input_number.alarm_clock_minute
          - input_boolean.alarm_clock_radio
          - input_boolean.alarm_clock_status
