title: Home Assistant
views:
  - title: Control
    cards:
      - type: entities
        entities:
          - scene.normal
          - scene.dark
          - scene.away
          - scene.night
          - scene.away
      - type: thermostat
        entity: climate.woonkamer
      - type: entities
        entities:
          - script.open_covers
          - script.close_covers
  - title: Media
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - input_select.radio_station
          - script.radio
      - type: media-control
        entity: media_player.lg_webos_smart_tv
      - type: media-control
        entity: media_player.nad7050
      - type: media-control
        entity: media_player.chromecast_audio
      - type: entities
        entities:
          - scene.movie
          - scene.dark
          - scene.normal
          - script.netflix
          - script.youtube
          - script.npo
          - script.disney
          - entity: switch.tradfri_outlet
            name: stereo power
  - title: Lights
    cards:
      - type: light
        entity: light.livingroom_back
      - type: light
        entity: light.livingroom_left
      - type: light
        entity: light.livingroom_right
      - type: light
        entity: light.livingroom_corner
      - type: entities
        entities:
          - switch.bookcase_light
          - switch.kitchen_light_left
          - switch.kitchen_light_right
      - type: light
        entity: light.reading
      - type: light
        entity: light.bedroomstrip
  - title: Data
    cards:
      - type: picture-entity
        entity: camera.buienradar_loop
      - type: weather-forecast
        entity: weather.br_unknown_station
      - type: glance
        entities:
          - entity: sensor.livingroom_temperature
            name: Living
          - entity: sensor.hall_temperature
            name: Hall
          - entity: sensor.qubino_zmnhcdx_flush_shutter_temperature
            name: Upstairs
          - entity: sensor.kitchen_temperature
            name: Kitchen
          - entity: sensor.restroom_temperature
            name: Restroom
      - type: sensor
        entity: sensor.power_consumption
        graph: line
        detail: 2
      - type: sensor
        entity: sensor.power_production
        graph: line
        detail: 2
      - type: sensor
        entity: sensor.download
        graph: line
        hours_to_show: 1
        detail: 2
      - type: sensor
        entity: sensor.upload
        graph: line
        hours_to_show: 1
        detail: 2

  - title: Covers
    cards:
      - type: entities
        entities:
          - entity: cover.qubino_zmnhcdx_flush_shutter_switch
            name: kitchen
          - entity: cover.qubino_zmnhcdx_flush_shutter_switch_2
            name: livingroom_left
          - entity: cover.qubino_zmnhcdx_flush_shutter_switch_3
            name: livingroom_right
          - entity: cover.qubino_zmnhcdx_flush_shutter_switch_4
            name: upstairs_side
          - entity: cover.qubino_zmnhcdx_flush_shutter_switch_5
            name: upstairs_front
  - title: Clock
    cards:
      - type: entities
        entities:
          - sensor.alarm_clock_time
          - input_number.alarm_clock_hour
          - input_number.alarm_clock_minute
          - input_boolean.alarm_clock_radio
          - input_boolean.alarm_clock_status
