title: Home Assistant
views:
  - title: Control
    cards:
      - type: entities
        entities:
          - scene.normal
          - scene.dark
          - scene.away
      - type: thermostat
        entity: climate.woonkamer
      - type: entities
        entities:
          - scene.open
          - scene.closed
  - title: Media
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - input_select.radio_station
          - script.radio
      - type: media-control
        entity: media_player.lg_webos_smart_tv
      - type: media-control
        entity: media_player.nad7050
      - type: media-control
        entity: media_player.chromecast_audio
      - type: entities
        entities:
          - scene.tv
          - scene.movie
          - scene.dark
          - scene.normal
          - entity: switch.tradfri_outlet
            name: stereo power
  - title: Lights
    cards:
      - type: light
        entity: light.livingroom_back
      - type: light
        entity: light.livingroom_left
      - type: light
        entity: light.livingroom_right
      - type: light
        entity: light.livingroom_corner
      - type: entities
        entities:
          - switch.bookcase_light
          - switch.kitchen_light_left
          - switch.kitchen_light_right
  - title: Data
    cards:
      - type: glance
        entities:
          - entity: sensor.livingroom_temperature
            name: Living
          - entity: sensor.hall_temperature
            name: Hall
          - entity: sensor.qubino_zmnhcdx_flush_shutter_temperature
            name: Upstairs
          - entity: sensor.kitchen_temperature
            name: Kitchen
          - entity: sensor.restroom_temperature
            name: Restroom
      - type: sensor
        entity: sensor.power_consumption
        graph: line
        detail: 2
      - type: sensor
        entity: sensor.power_production
        graph: line
        detail: 2
      - type: sensor
        entity: sensor.livingroom_temperature
        graph: line
      - type: sensor
        entity: sensor.download
        graph: line
        hours_to_show: 1
        detail: 2
      - type: sensor
        entity: sensor.upload
        graph: line
        hours_to_show: 1
        detail: 2

  - title: Clock
    cards:
      - type: entities
        entities:
          - sensor.alarm_clock_time
          - input_number.alarm_clock_hour
          - input_number.alarm_clock_minute
          - input_boolean.alarm_clock_radio
          - input_boolean.alarm_clock_status
